name: Racket

on:
  schedule:
    - cron: "0 9 * * *"
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: [ '7.9', '8.0', 'current' ]
    steps:
    - uses: actions/checkout@master
    - name: Setup Racket
      uses: Bogdanp/setup-racket@v1.2.1
      with:
        architecture: 'x64'   # (x64 or x86), ignored on Linux
        version: ${{ matrix.racket-version }}        # or 'current' for the latest snapshot
    - run: raco pkg install --auto
    - run: raco test .
